// 错误码
module.exports = {
  "success": {code: 0, msg: '请求成功'},
  "error": {code: 1, msg: '请求失败'},
  "error_unknown": {code: 100, msg: '未知错误'},
  "error_format": {code: 101, msg: '错误格式'},
  "error_wrongdata": {code: 102, msg: '错误数据'},
  "error_nodata": {code: 104, msg: '暂无数据'},
  "error_json_format": {code: 105, msg: 'jsong格式不正确'},
  "error_body": {code: 106, msg: '请求参数不正确'},
  "error_body_cmd": {code: 108, msg: '请求参数cmd不能为空'},
  "error_body_data": {code: 113, msg: '请求参数data不能为空'},
  "error_noroute": {code: 109, msg: '找不到此路由'},
  "error_database": {code: 110, msg: '数据库错误'},
  "error_notfinddata": {code: 111, msg: '找不到数据'},
  "error_validation": {code: 112, msg: '数据验证错误'},
  "error_notlogin": {code: 120, msg: '未登录'},
  "error_right_limited": {code: 121, msg: '不正确限制'},
  "error_noaccount": {code: 103, msg: '没用户名'},
  "error_nopasswd": {code: 202, msg: '没密码'},
  "error_account_exist": {code: 211, msg: '此用户已存在'},
  "error_account_noexist": {code: 212, msg: '此用户不存在'},
  "error_account_or_passwd": {code: 221, msg: '帐号或密码不正确'},
  "error_login_wrong_data": {code: 222, msg: '登录错误数据'},
  "error_login_already_in": {code: 230, msg: '已登录'},
  "error_login_already_out": {code: 231, msg: '已退出'},
  "error_login_in_timeout": {code: 232, msg: '登录超时'},
  "error_token_verify": {code: 233, msg: 'token验证失败'},
};
